services:
  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8001:8000
    environment:
      - ENVIRONMENT=dev
      - TESTNIG=0
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web-dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@web-db:5432/web-test

