services:
  web:
    build:
      context: ./project
      args:
        ENV: dev
    command: python -m uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - ./project/.env-dev
    
    volumes:
      - ./project:/usr/src/app
    ports:
      - 8001:8000